# Generated by Django 4.0.1 on 2022-01-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robos',
            name='robocode',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
